name: NonsenseApp CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run npm Install
        run: npm ci
      - name: Run npm ESLint
        run: npm run lint
      - name: Run prettier
        run: npm run format
      - name: Run tests
        run: npm run test
